### ISSUE TITLE
Add info of each wiki in the list of wikis for selection

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#13]
First, change the name of the wiki to an operative name. Is there a unique id name for each wiki? If not, don't panic, the rest of the information shown should disambiguate the wiki.
Information that could  be show is:
- Year-month of creation
- Number of users (as of the dum date)
- Number of articles (as of the dum date)
- Year-month of the dump
- Link to the wiki home (it could be added as a hyperlink in the wiki name)
- Logo (it could also link ot the wikihome).

**Comment by Akronix** [comment]
There is a unique wikia id for every wiki but it isn't descriptive at all.
However, we could use the wiki name which is good enough for identifying a wiki, and then show the other details you listed.

**Comment by Akronix** [comment]
We need to generate a JSON file per wiki from the csv data and from the wiki site which contains all this info that is going to be shown in the wikichron interface.
Preferably using the csv data to extract this information rather than using the wikia statistics endpoint. In this way, we will be displaying the same wiki info as that shown in the metrics.

**Comment by Akronix** [comment]
This will be fixed elegantly in the version 2 of WikiChron.
