### ISSUE TITLE
[New metric] Total edits per user

### ISSUE THREAD

**Issue by Akronix** [Grasia/WikiChron#39]
Question @javiag : what we want here, total active users or total users?

**Comment by Akronix** [comment]
Either we decide to take active users or total users, same should be taken for "Total articles edits per user" metric which currently it's taken total users. However, mind that anonymous edits are not considered globally, but just the edits of the last month, closer to the active users approach.

**Comment by javiag** [comment]
They are total users. Total Active users should be the same number in principle, but the term is messy.
However, the names of: 
- Edits per user
- Article edits per user
Should be active users, otherwise the ratio is very small. Anyway, the name should change to
- Edits per active user
- Article edits per active user

Regarding the metrics of anonymous participants, we do not estimate their "productivity" ratios. BUT we count them in the general productivity metrics under the term "user", e.g. edits per user.

Please, check in this general metrics we do group anonymous users by IP as intended.

**Comment by javiag** [comment]
I have created issue #91 to refer to the coherence in the name and computation of users and active users.

In this way, the present issue only attains to the creation of the metric "total edits per user".
