### ISSUE TITLE
Add user roles to wikis.json data

### ISSUE THREAD

**Issue by Akronix** [Grasia/WikiChron#57]
For some metrics and analysis, it could be interesting to have the user ids of some formal roles in the wiki:

- Wiki administrators
- Wiki Bureaucrats
- FANDOM staff

It should be added to the wikis.json additionally to the botsids info.

More on user groups and rights: https://community.wikia.com/wiki/Help:User_rights

**Comment by javiag** [comment]
In wikis.json? Why there?

I think that regarding roles in the wiki two things could be of interest to reflect in WikiChron:

- Counting the number of "adminsitrators", "bureacrats", etc in the wiki each month. This number can increase or decrease as time goes by.
- Counting the edits made by "administrators", "bureaucrats", etc in the wiki each month in order to separate it from edits by "regular" editors. This metrics would require to track whether an edit was made by a user CURRENTLY, i.e. at the time of the edit, holds a formal role in the wiki.

**Comment by Akronix** [comment]
We don't have the user role reflected in the wiki dump, so we need it to get it from Special:ListUsers page ([go here for an example](https://gardening.wikia.com/wiki/Special:ListUsers?group=sysop)), and, therefore, we can't track the change on admins or bureaucrats through time.

What we can do is to separate edits made by these roles from regular editors, but we cannot distinguish if an admin was not an admin in the moment of the edit. We would have to count the edits with the role they have when we get these roles from the wiki and we add those roles to the `wikis.json` file.
Fortunately for us, these roles aren't something that changes very often and commonly these users have come with some reputation or activity level beyond the regular editor prior to become a powered user within the wiki.

**Comment by javiag** [comment]
You are right. 

Since we cannot track how the roles of administrators, bureacrats, etc change through time (users promoted and users that leave the role, etc), then I think this is not an interesting feature for wikichron.

Any assumption that we may take about edits made by administrators, bureacrats, etc will probably be wrong at some time. So, I will forget about this issue and will close it. What do you think?

In fact, what we have in mind for the close feature of "classifying" editors according to their activity is probably more interesting than this, or at least is another way of spliting edits intog groups.

What do you think @Akronix?

**Comment by Akronix** [comment]
Agreed. Let's close this unless we find a way to know when users get promoted to their roles.
